/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  PromptValuesApi,
  FeedbackBadgesApi,
  GiveRequestedFeedbackEventsApi,
  WorkersApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { WorkdayPerformanceEnablementCustom } from "./client-custom";

export class WorkdayPerformanceEnablement extends WorkdayPerformanceEnablementCustom {
  readonly promptValues: PromptValuesApi;
  readonly feedbackBadges: FeedbackBadgesApi;
  readonly giveRequestedFeedbackEvents: GiveRequestedFeedbackEventsApi;
  readonly workers: WorkersApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.promptValues = new PromptValuesApi(configuration);
    this.feedbackBadges = new FeedbackBadgesApi(configuration);
    this.giveRequestedFeedbackEvents = new GiveRequestedFeedbackEventsApi(configuration);
    this.workers = new WorkersApi(configuration);
  }

}
