/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Event about \\~Worker\\~ for Facet Search
 * @export
 * @interface AboutWorkerD396fd5bffec1000100f44a5808f0005
 */
export interface AboutWorkerD396fd5bffec1000100f44a5808f0005 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof AboutWorkerD396fd5bffec1000100f44a5808f0005
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof AboutWorkerD396fd5bffec1000100f44a5808f0005
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof AboutWorkerD396fd5bffec1000100f44a5808f0005
     */
    'href'?: string;
}

