/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ActivityStreamableItemSummary88d272af423b100036fc19a90e210000AllOf } from './activity-streamable-item-summary88d272af423b100036fc19a90e210000-all-of';

/**
 * 
 * @export
 * @interface ActivityStreamableItemSummary88d272af423b100036fc19a90e210000
 */
export interface ActivityStreamableItemSummary88d272af423b100036fc19a90e210000 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof ActivityStreamableItemSummary88d272af423b100036fc19a90e210000
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof ActivityStreamableItemSummary88d272af423b100036fc19a90e210000
     */
    'descriptor'?: string;
}

