/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * a set containing no instances
 * @export
 * @interface Action38ff08ab6736100010816009079d0126
 */
export interface Action38ff08ab6736100010816009079d0126 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof Action38ff08ab6736100010816009079d0126
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof Action38ff08ab6736100010816009079d0126
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof Action38ff08ab6736100010816009079d0126
     */
    'href'?: string;
}

