/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000AllOf
 */
export interface AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000AllOf {
    /**
     * Id of the instance
     * @type {string}
     * @memberof AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000AllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000AllOf
     */
    'descriptor'?: string;
}

