/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The feedback badge included with the feedback given event to the subject.
 * @export
 * @interface BadgeAfd6ac52d62510001357f891ccfd0003
 */
export interface BadgeAfd6ac52d62510001357f891ccfd0003 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof BadgeAfd6ac52d62510001357f891ccfd0003
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof BadgeAfd6ac52d62510001357f891ccfd0003
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof BadgeAfd6ac52d62510001357f891ccfd0003
     */
    'href'?: string;
}

