/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Action38ff08ab6736100010816009079d0126 } from './action38ff08ab6736100010816009079d0126';
import { BusinessProcessParametersAfd6ac52d6251000117be546cb060000 } from './business-process-parameters-afd6ac52d6251000117be546cb060000';
import { Comments86093b8a932f10001499f356ff83012e } from './comments86093b8a932f10001499f356ff83012e';
import { EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143 } from './event-attachments-for-toolbar43b30ba735b8100011ee4767246d0143';
import { For5d688bd57bb910001815ab3dd10024a9 } from './for5d688bd57bb910001815ab3dd10024a9';
import { OverallBusinessProcess5d688bd57bb910001815ab49927724aa } from './overall-business-process5d688bd57bb910001815ab49927724aa';
import { TransactionStatus7457adcbe0fa1000089b63ab3a510000 } from './transaction-status7457adcbe0fa1000089b63ab3a510000';

/**
 * The Action Event instance to be used with businessProcessLinkable linked service representations.
 * @export
 * @interface BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000
 */
export interface BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000 {
    /**
     * 
     * @type {Action38ff08ab6736100010816009079d0126}
     * @memberof BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000
     */
    'action': Action38ff08ab6736100010816009079d0126;
    /**
     * 
     * @type {OverallBusinessProcess5d688bd57bb910001815ab49927724aa}
     * @memberof BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000
     */
    'overallBusinessProcess'?: OverallBusinessProcess5d688bd57bb910001815ab49927724aa;
    /**
     * Returns a null.
     * @type {string}
     * @memberof BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000
     */
    'comment'?: string;
    /**
     * Returns the comments for the current business process.
     * @type {Array<Comments86093b8a932f10001499f356ff83012e>}
     * @memberof BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000
     */
    'comments'?: Array<Comments86093b8a932f10001499f356ff83012e>;
    /**
     * 
     * @type {TransactionStatus7457adcbe0fa1000089b63ab3a510000}
     * @memberof BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000
     */
    'transactionStatus'?: TransactionStatus7457adcbe0fa1000089b63ab3a510000;
    /**
     * Warning message for an action event triggered by a condition.
     * @type {string}
     * @memberof BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000
     */
    'warningValidations'?: string;
    /**
     * The current status of the business process.  For example: Successfully Completed, Denied, Terminated.
     * @type {string}
     * @memberof BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000
     */
    'overallStatus'?: string;
    /**
     * Returns attachments associated with this business process that are uploaded from the toolbar and are accessible to the processing person. Returns blank if either of these conditions are not met.
     * @type {Array<EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143>}
     * @memberof BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000
     */
    'attachments'?: Array<EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143>;
    /**
     * Validation message for an action event triggered by a condition.
     * @type {string}
     * @memberof BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000
     */
    'criticalValidations'?: string;
    /**
     * 
     * @type {For5d688bd57bb910001815ab3dd10024a9}
     * @memberof BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000
     */
    'for'?: For5d688bd57bb910001815ab3dd10024a9;
}

