/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CategorySummary88d272af423b100036e57ea69d570000AllOf
 */
export interface CategorySummary88d272af423b100036e57ea69d570000AllOf {
    /**
     * Id of the instance
     * @type {string}
     * @memberof CategorySummary88d272af423b100036e57ea69d570000AllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CategorySummary88d272af423b100036e57ea69d570000AllOf
     */
    'descriptor'?: string;
}

