/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Returns the category of a Business Process Attachment.
 * @export
 * @interface Category43b30ba735b8100011ee4781a9d50146
 */
export interface Category43b30ba735b8100011ee4781a9d50146 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof Category43b30ba735b8100011ee4781a9d50146
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof Category43b30ba735b8100011ee4781a9d50146
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof Category43b30ba735b8100011ee4781a9d50146
     */
    'href'?: string;
}

