/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Content type of the attachment
 * @export
 * @interface ContentType43b30ba735b8100011ee47993f11014a
 */
export interface ContentType43b30ba735b8100011ee47993f11014a {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof ContentType43b30ba735b8100011ee47993f11014a
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof ContentType43b30ba735b8100011ee47993f11014a
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof ContentType43b30ba735b8100011ee47993f11014a
     */
    'href'?: string;
}

