/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026e } from './country-data-for-location-data-af21e47ff7c01000092e0e4f9a22026e';

/**
 * Returns the \\~country\\~ from the primary address for the location.
 * @export
 * @interface CountryAf21e47ff7c01000092ecf4d7ad30270
 */
export interface CountryAf21e47ff7c01000092ecf4d7ad30270 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CountryAf21e47ff7c01000092ecf4d7ad30270
     */
    'descriptor'?: string;
}

