/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026eAllOf
 */
export interface CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026eAllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026eAllOf
     */
    'descriptor'?: string;
}

