/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The \\~worker\\~ that initially created or added this \\~goal\\~.
 * @export
 * @interface CreatedBy88d272af423b100036b561a7784b0000
 */
export interface CreatedBy88d272af423b100036b561a7784b0000 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof CreatedBy88d272af423b100036b561a7784b0000
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof CreatedBy88d272af423b100036b561a7784b0000
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof CreatedBy88d272af423b100036b561a7784b0000
     */
    'href'?: string;
}

