/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Category43b30ba735b8100011ee4781a9d50146 } from './category43b30ba735b8100011ee4781a9d50146';
import { ContentType43b30ba735b8100011ee47993f11014a } from './content-type43b30ba735b8100011ee47993f11014a';
import { EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143AllOf } from './event-attachments-for-toolbar43b30ba735b8100011ee4767246d0143-all-of';
import { UploadedByB32ff437243510000e22e06470370160 } from './uploaded-by-b32ff437243510000e22e06470370160';

/**
 * 
 * @export
 * @interface EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143
 */
export interface EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143 {
    /**
     * Event attachment description
     * @type {string}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143
     */
    'description'?: string;
    /**
     * 
     * @type {ContentType43b30ba735b8100011ee47993f11014a}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143
     */
    'contentType'?: ContentType43b30ba735b8100011ee47993f11014a;
    /**
     * File length of the attachment
     * @type {number}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143
     */
    'fileLength'?: number;
    /**
     * Returns Date the Business Process Attachment was updated.
     * @type {string}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143
     */
    'uploadDate'?: string;
    /**
     * File name of the attachment
     * @type {string}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143
     */
    'fileName'?: string;
    /**
     * 
     * @type {UploadedByB32ff437243510000e22e06470370160}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143
     */
    'uploadedBy'?: UploadedByB32ff437243510000e22e06470370160;
    /**
     * 
     * @type {Category43b30ba735b8100011ee4781a9d50146}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143
     */
    'category'?: Category43b30ba735b8100011ee4781a9d50146;
    /**
     * Id of the instance
     * @type {string}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143
     */
    'id'?: string;
}

