/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FACETSMODELREFERENCEInnerValuesInner
 */
export interface FACETSMODELREFERENCEInnerValuesInner {
    /**
     * The number of instances returned by this facet
     * @type {number}
     * @memberof FACETSMODELREFERENCEInnerValuesInner
     */
    'count'?: number;
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof FACETSMODELREFERENCEInnerValuesInner
     */
    'id': string;
    /**
     * A description of the facet
     * @type {string}
     * @memberof FACETSMODELREFERENCEInnerValuesInner
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof FACETSMODELREFERENCEInnerValuesInner
     */
    'href'?: string;
}

