/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FACETSMODELREFERENCEInnerValuesInner } from './facetsmodelreferenceinner-values-inner';

/**
 * This object represents the possible facets for this resource
 * @export
 * @interface FACETSMODELREFERENCEInner
 */
export interface FACETSMODELREFERENCEInner {
    /**
     * A description of the facet
     * @type {string}
     * @memberof FACETSMODELREFERENCEInner
     */
    'descriptor'?: string;
    /**
     * The alias used to select the facet
     * @type {string}
     * @memberof FACETSMODELREFERENCEInner
     */
    'facetParameter'?: string;
    /**
     * the facet values
     * @type {Array<FACETSMODELREFERENCEInnerValuesInner>}
     * @memberof FACETSMODELREFERENCEInner
     */
    'values'?: Array<FACETSMODELREFERENCEInnerValuesInner>;
}

