/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * This report field returns the feedback templates used to obtain \\~employee\\~ feedback.
 * @export
 * @interface FeedbackTemplate4db9c44d36231000134c7b8eb3800000
 */
export interface FeedbackTemplate4db9c44d36231000134c7b8eb3800000 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof FeedbackTemplate4db9c44d36231000134c7b8eb3800000
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof FeedbackTemplate4db9c44d36231000134c7b8eb3800000
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof FeedbackTemplate4db9c44d36231000134c7b8eb3800000
     */
    'href'?: string;
}

