/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedbackBadgeIconD4d355b2d3db100020b8608b75250016 } from './feedback-badge-icon-d4d355b2d3db100020b8608b75250016';

/**
 * 
 * @export
 * @interface FeedbackBadgeDetail9eab868ca81410001402525d054211f7AllOf
 */
export interface FeedbackBadgeDetail9eab868ca81410001402525d054211f7AllOf {
    /**
     * 
     * @type {FeedbackBadgeIconD4d355b2d3db100020b8608b75250016}
     * @memberof FeedbackBadgeDetail9eab868ca81410001402525d054211f7AllOf
     */
    'feedbackBadgeIcon'?: FeedbackBadgeIconD4d355b2d3db100020b8608b75250016;
    /**
     * Returns the Workday ID for a given object.
     * @type {string}
     * @memberof FeedbackBadgeDetail9eab868ca81410001402525d054211f7AllOf
     */
    'workdayID'?: string;
    /**
     * The Reference ID to use for lookups within our Workday Web Services. For supervisory organizations, this is also the \'Organization ID\'
     * @type {string}
     * @memberof FeedbackBadgeDetail9eab868ca81410001402525d054211f7AllOf
     */
    'feedbackBadgeID'?: string;
    /**
     * The name of this feedback badge.
     * @type {string}
     * @memberof FeedbackBadgeDetail9eab868ca81410001402525d054211f7AllOf
     */
    'name'?: string;
}

