/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BadgeAfd6ac52d62510001357f891ccfd0003 } from './badge-afd6ac52d62510001357f891ccfd0003';
import { BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000 } from './business-process-parameters-afd6ac52d6251000117d0a60ed8b0000';
import { FromWorkerAfd6ac52d62510001357f891ccfd0001 } from './from-worker-afd6ac52d62510001357f891ccfd0001';
import { GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302 } from './get-workers-feedback-also-about3ab333661034100010b5635b2f7a0302';
import { RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000 } from './related-feedback-events9708c966f04f10000e1e9b7f9a5c0000';
import { RelatesTo9d12ad407f0f10001c3949add7d40000 } from './relates-to9d12ad407f0f10001c3949add7d40000';
import { ToWorkerF4946919a39f10000f03207b1f230000 } from './to-worker-f4946919a39f10000f03207b1f230000';
import { WorkersToNotify9e478586f65410001035b6c26a4c0000 } from './workers-to-notify9e478586f65410001035b6c26a4c0000';

/**
 * 
 * @export
 * @interface FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
 */
export interface FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf {
    /**
     * 
     * @type {ToWorkerF4946919a39f10000f03207b1f230000}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'toWorker'?: ToWorkerF4946919a39f10000f03207b1f230000;
    /**
     * The workers that were selected to be notified of the feedback given event.
     * @type {Array<WorkersToNotify9e478586f65410001035b6c26a4c0000>}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'workersToNotify'?: Array<WorkersToNotify9e478586f65410001035b6c26a4c0000>;
    /**
     * 
     * @type {RelatesTo9d12ad407f0f10001c3949add7d40000}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'relatesTo'?: RelatesTo9d12ad407f0f10001c3949add7d40000;
    /**
     * 
     * @type {BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'businessProcessParameters'?: BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000;
    /**
     * The other workers this feedback event is about.
     * @type {Array<GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302>}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'feedbackAlsoAbout'?: Array<GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302>;
    /**
     * True if the feedback event is confidential between the feedback provider and the manager. Workers don\'t see confidential feedback.
     * @type {boolean}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'hiddenFromWorker'?: boolean;
    /**
     * True if the feedback event is private between the feedback provider and the worker. Private feedback isn\'t shared with managers.
     * @type {boolean}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'hiddenFromManager'?: boolean;
    /**
     * The comment text for an anytime feedback event.
     * @type {string}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'comment'?: string;
    /**
     * 
     * @type {FromWorkerAfd6ac52d62510001357f891ccfd0001}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'fromWorker'?: FromWorkerAfd6ac52d62510001357f891ccfd0001;
    /**
     * 
     * @type {BadgeAfd6ac52d62510001357f891ccfd0003}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'badge'?: BadgeAfd6ac52d62510001357f891ccfd0003;
    /**
     * The anytime feedback events for the multiple recipients event.
     * @type {Array<RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000>}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'relatedFeedbackEvents'?: Array<RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000>;
    /**
     * The date the feedback was provided.
     * @type {string}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'feedbackGivenDate'?: string;
    /**
     * True if the feedback provider\'s name has chosen to be displayed. Names not chosen to be displayed are not shared.
     * @type {boolean}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'showFeedbackProviderName'?: boolean;
    /**
     * A link to the instance
     * @type {string}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'href'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    'descriptor'?: string;
}

