/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Returns Icon for Feedback Badge
 * @export
 * @interface FeedbackBadgeIconD4d355b2d3db100020b8608b75250016
 */
export interface FeedbackBadgeIconD4d355b2d3db100020b8608b75250016 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof FeedbackBadgeIconD4d355b2d3db100020b8608b75250016
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof FeedbackBadgeIconD4d355b2d3db100020b8608b75250016
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof FeedbackBadgeIconD4d355b2d3db100020b8608b75250016
     */
    'href'?: string;
}

