/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The person who gave the feedback (responder).
 * @export
 * @interface FeedbackResponder2f703c317dc910001c16504848720001
 */
export interface FeedbackResponder2f703c317dc910001c16504848720001 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof FeedbackResponder2f703c317dc910001c16504848720001
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof FeedbackResponder2f703c317dc910001c16504848720001
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof FeedbackResponder2f703c317dc910001c16504848720001
     */
    'href'?: string;
}

