/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The feedback question unique to the feedback event. Includes ad-hoc feedback questions.
 * @export
 * @interface FeedbackQuestionD396fd5bffec10001393481822cd0007
 */
export interface FeedbackQuestionD396fd5bffec10001393481822cd0007 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof FeedbackQuestionD396fd5bffec10001393481822cd0007
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof FeedbackQuestionD396fd5bffec10001393481822cd0007
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof FeedbackQuestionD396fd5bffec10001393481822cd0007
     */
    'href'?: string;
}

