/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The \\~worker\\~ this feedback event is about. This CRF should only be utilized for anytime feedback events.
 * @export
 * @interface FeedbackAbout4db9c44d36231000134c7b8eb3800003
 */
export interface FeedbackAbout4db9c44d36231000134c7b8eb3800003 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof FeedbackAbout4db9c44d36231000134c7b8eb3800003
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof FeedbackAbout4db9c44d36231000134c7b8eb3800003
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof FeedbackAbout4db9c44d36231000134c7b8eb3800003
     */
    'href'?: string;
}

