/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedbackBadgeDetail9eab868ca81410001402525d054211f7 } from './feedback-badge-detail9eab868ca81410001402525d054211f7';

/**
 * 
 * @export
 * @interface FeedbackBadgesGetCollectionResponse
 */
export interface FeedbackBadgesGetCollectionResponse {
    /**
     * 
     * @type {Array<FeedbackBadgeDetail9eab868ca81410001402525d054211f7>}
     * @memberof FeedbackBadgesGetCollectionResponse
     */
    'data'?: Array<FeedbackBadgeDetail9eab868ca81410001402525d054211f7>;
    /**
     * 
     * @type {number}
     * @memberof FeedbackBadgesGetCollectionResponse
     */
    'total'?: number;
}

