/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000AllOf } from './feedback-responders-ffdd5de32f7f100016dbb1b188d70000-all-of';

/**
 * 
 * @export
 * @interface FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000
 */
export interface FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000
     */
    'descriptor'?: string;
}

