/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedbackResponder2f703c317dc910001c16504848720001 } from './feedback-responder2f703c317dc910001c16504848720001';
import { FeedbackResponse2f703c317dc910001bd2de83d1590000AllOf } from './feedback-response2f703c317dc910001bd2de83d1590000-all-of';

/**
 * 
 * @export
 * @interface FeedbackResponse2f703c317dc910001bd2de83d1590000
 */
export interface FeedbackResponse2f703c317dc910001bd2de83d1590000 {
    /**
     * The feedback response for a feedback question.
     * @type {string}
     * @memberof FeedbackResponse2f703c317dc910001bd2de83d1590000
     */
    'response'?: string;
    /**
     * Returns True if the responder declined to submit a response to a specific feedback question.
     * @type {boolean}
     * @memberof FeedbackResponse2f703c317dc910001bd2de83d1590000
     */
    'feedbackDeclined'?: boolean;
    /**
     * The reason a requested feedback question was declined.
     * @type {string}
     * @memberof FeedbackResponse2f703c317dc910001bd2de83d1590000
     */
    'feedbackDeclineReason'?: string;
    /**
     * 
     * @type {FeedbackResponder2f703c317dc910001c16504848720001}
     * @memberof FeedbackResponse2f703c317dc910001bd2de83d1590000
     */
    'feedbackResponder'?: FeedbackResponder2f703c317dc910001c16504848720001;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof FeedbackResponse2f703c317dc910001bd2de83d1590000
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof FeedbackResponse2f703c317dc910001bd2de83d1590000
     */
    'id'?: string;
}

