/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The \\~worker\\~ that provided the feedback event. Only if the request asked to know the identity of the person responding, then this is returned.
 * @export
 * @interface FromWorkerAfd6ac52d62510001357f891ccfd0001
 */
export interface FromWorkerAfd6ac52d62510001357f891ccfd0001 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof FromWorkerAfd6ac52d62510001357f891ccfd0001
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof FromWorkerAfd6ac52d62510001357f891ccfd0001
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof FromWorkerAfd6ac52d62510001357f891ccfd0001
     */
    'href'?: string;
}

