/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302AllOf } from './get-workers-feedback-also-about3ab333661034100010b5635b2f7a0302-all-of';

/**
 * 
 * @export
 * @interface GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302
 */
export interface GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302
     */
    'descriptor'?: string;
}

