/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000AllOf
 */
export interface GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000AllOf
     */
    'id'?: string;
}

