/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AboutWorkerD396fd5bffec1000100f44a5808f0005 } from './about-worker-d396fd5bffec1000100f44a5808f0005';
import { BusinessProcessParametersD396fd5bffec1000100f440bde4c0001 } from './business-process-parameters-d396fd5bffec1000100f440bde4c0001';
import { RequestedByD396fd5bffec1000100f44a5808f0006 } from './requested-by-d396fd5bffec1000100f44a5808f0006';
import { RequestedFeedbackCommentsD396fd5bffec10001393477e77870000 } from './requested-feedback-comments-d396fd5bffec10001393477e77870000';

/**
 * 
 * @export
 * @interface GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
 */
export interface GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf {
    /**
     * The date the business process needs to be completed.
     * @type {string}
     * @memberof GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
     */
    'dueDate'?: string;
    /**
     * The date the feedback was provided.
     * @type {string}
     * @memberof GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
     */
    'feedbackGivenDate'?: string;
    /**
     * The date the feedback event was created.
     * @type {string}
     * @memberof GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
     */
    'feedbackCreationDate'?: string;
    /**
     * 
     * @type {RequestedByD396fd5bffec1000100f44a5808f0006}
     * @memberof GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
     */
    'requestedBy'?: RequestedByD396fd5bffec1000100f44a5808f0006;
    /**
     * 
     * @type {AboutWorkerD396fd5bffec1000100f44a5808f0005}
     * @memberof GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
     */
    'aboutWorker'?: AboutWorkerD396fd5bffec1000100f44a5808f0005;
    /**
     * The date the feedback request expires.
     * @type {string}
     * @memberof GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
     */
    'expirationDate'?: string;
    /**
     * True if the feedback provider\'s name is not displayed.
     * @type {boolean}
     * @memberof GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
     */
    'displayNameofResponder'?: boolean;
    /**
     * The feedback comments for this feedback event. To include feedback comments in reports or notifications intended for Employees, use Feedback Comments for Self-Service Reporting instead.
     * @type {Array<RequestedFeedbackCommentsD396fd5bffec10001393477e77870000>}
     * @memberof GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
     */
    'feedbackComments'?: Array<RequestedFeedbackCommentsD396fd5bffec10001393477e77870000>;
    /**
     * 
     * @type {BusinessProcessParametersD396fd5bffec1000100f440bde4c0001}
     * @memberof GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
     */
    'businessProcessParameters'?: BusinessProcessParametersD396fd5bffec1000100f440bde4c0001;
    /**
     * Yes if the feedback is private between the feedback provider and the worker.
     * @type {boolean}
     * @memberof GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
     */
    'feedbackPrivate'?: boolean;
    /**
     * Yes if the feedback is confidential between the feedback provider and the manager. Employees, or who the feedback is about, don\'t see confidential feedback.
     * @type {boolean}
     * @memberof GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
     */
    'feedbackConfidential'?: boolean;
    /**
     * Id of the instance
     * @type {string}
     * @memberof GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
     */
    'descriptor'?: string;
}

