/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000 } from './give-requested-feedback-details-d396fd5bffec10000e3eba1a70440000';

/**
 * 
 * @export
 * @interface GiveRequestedFeedbackEventsGetCollectionFeedbackEventsResponse
 */
export interface GiveRequestedFeedbackEventsGetCollectionFeedbackEventsResponse {
    /**
     * 
     * @type {Array<GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000>}
     * @memberof GiveRequestedFeedbackEventsGetCollectionFeedbackEventsResponse
     */
    'data'?: Array<GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000>;
    /**
     * 
     * @type {number}
     * @memberof GiveRequestedFeedbackEventsGetCollectionFeedbackEventsResponse
     */
    'total'?: number;
}

