/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ActivityStreamableItemSummary88d272af423b100036fc19a90e210000 } from './activity-streamable-item-summary88d272af423b100036fc19a90e210000';
import { AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000 } from './associated-reviews-summary2c793e888bcd1000346e381955dd0000';
import { CategorySummary88d272af423b100036e57ea69d570000 } from './category-summary88d272af423b100036e57ea69d570000';
import { CreatedBy88d272af423b100036b561a7784b0000 } from './created-by88d272af423b100036b561a7784b0000';
import { RelatesToSummary2c793e888bcd100034b42ada01b20000 } from './relates-to-summary2c793e888bcd100034b42ada01b20000';
import { Status9df8579a128710001ac8e9879d1f0001 } from './status9df8579a128710001ac8e9879d1f0001';
import { Supports9df8579a128710001ac8e9879d1f0000 } from './supports9df8579a128710001ac8e9879d1f0000';
import { Worker47e98fa91eee100017c2c78c80410000 } from './worker47e98fa91eee100017c2c78c80410000';

/**
 * 
 * @export
 * @interface GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
 */
export interface GoalsSummary2c793e888bcd100033e663075a2b0000AllOf {
    /**
     * The description of the goal.
     * @type {string}
     * @memberof GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    'description'?: string;
    /**
     * The name of the goal.
     * @type {string}
     * @memberof GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    'name'?: string;
    /**
     * The tags included with the goal.
     * @type {Array<RelatesToSummary2c793e888bcd100034b42ada01b20000>}
     * @memberof GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    'relatesTo'?: Array<RelatesToSummary2c793e888bcd100034b42ada01b20000>;
    /**
     * The activity stream associated with the goal.
     * @type {Array<ActivityStreamableItemSummary88d272af423b100036fc19a90e210000>}
     * @memberof GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    'activityStreamableItem'?: Array<ActivityStreamableItemSummary88d272af423b100036fc19a90e210000>;
    /**
     * The date when the goal is due.
     * @type {string}
     * @memberof GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    'dueDate'?: string;
    /**
     * The associated reviews with the goal.
     * @type {Array<AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000>}
     * @memberof GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    'associatedReviews'?: Array<AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000>;
    /**
     * The category of the goal.
     * @type {Array<CategorySummary88d272af423b100036e57ea69d570000>}
     * @memberof GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    'category'?: Array<CategorySummary88d272af423b100036e57ea69d570000>;
    /**
     * 
     * @type {Supports9df8579a128710001ac8e9879d1f0000}
     * @memberof GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    'supports'?: Supports9df8579a128710001ac8e9879d1f0000;
    /**
     * 
     * @type {Worker47e98fa91eee100017c2c78c80410000}
     * @memberof GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    'worker'?: Worker47e98fa91eee100017c2c78c80410000;
    /**
     * 
     * @type {Status9df8579a128710001ac8e9879d1f0001}
     * @memberof GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    'status'?: Status9df8579a128710001ac8e9879d1f0001;
    /**
     * The date when the goal is completed.
     * @type {string}
     * @memberof GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    'completedOn'?: string;
    /**
     * 
     * @type {CreatedBy88d272af423b100036b561a7784b0000}
     * @memberof GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    'createdBy'?: CreatedBy88d272af423b100036b561a7784b0000;
    /**
     * The state of the goal. Indicates why the goal is non-editable or why a user needs to take an action to successfully create or update the goal. Possible values: Pending approval, Associated with In Progress Review, Pending archival, Pending restore, Saved for later, and Needs revising.
     * @type {string}
     * @memberof GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    'state'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    'id'?: string;
}

