/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INSTANCEMODELREFERENCE
 */
export interface INSTANCEMODELREFERENCE {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof INSTANCEMODELREFERENCE
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof INSTANCEMODELREFERENCE
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof INSTANCEMODELREFERENCE
     */
    'href'?: string;
}

