/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface JobTypeDataB8ac205877fd100005c3b50b74a30055AllOf
 */
export interface JobTypeDataB8ac205877fd100005c3b50b74a30055AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobTypeDataB8ac205877fd100005c3b50b74a30055AllOf
     */
    'descriptor'?: string;
}

