/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobProfileJobViewFab4a151b24810000d511d61ee641262AllOf } from './job-profile-job-view-fab4a151b24810000d511d61ee641262-all-of';

/**
 * 
 * @export
 * @interface JobProfileJobViewFab4a151b24810000d511d61ee641262
 */
export interface JobProfileJobViewFab4a151b24810000d511d61ee641262 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobProfileJobViewFab4a151b24810000d511d61ee641262
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof JobProfileJobViewFab4a151b24810000d511d61ee641262
     */
    'id'?: string;
}

