/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface JobProfileJobViewFab4a151b24810000d511d61ee641262AllOf
 */
export interface JobProfileJobViewFab4a151b24810000d511d61ee641262AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobProfileJobViewFab4a151b24810000d511d61ee641262AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof JobProfileJobViewFab4a151b24810000d511d61ee641262AllOf
     */
    'id'?: string;
}

