/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface JobWorkspaceData1005157e3d631000144205466a6c13d3AllOf
 */
export interface JobWorkspaceData1005157e3d631000144205466a6c13d3AllOf {
    /**
     * Location chain including bread crumbs for location.
     * @type {string}
     * @memberof JobWorkspaceData1005157e3d631000144205466a6c13d3AllOf
     */
    'locationChain'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobWorkspaceData1005157e3d631000144205466a6c13d3AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof JobWorkspaceData1005157e3d631000144205466a6c13d3AllOf
     */
    'id'?: string;
}

