/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobProfileJobViewFab4a151b24810000d511d61ee641262 } from './job-profile-job-view-fab4a151b24810000d511d61ee641262';

/**
 * The job profile for the position.
 * @export
 * @interface JobProfileB8ac205877fd10000ea9174f73c500aa
 */
export interface JobProfileB8ac205877fd10000ea9174f73c500aa {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobProfileB8ac205877fd10000ea9174f73c500aa
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof JobProfileB8ac205877fd10000ea9174f73c500aa
     */
    'id'?: string;
}

