/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobWorkspaceData1005157e3d631000144205466a6c13d3AllOf } from './job-workspace-data1005157e3d631000144205466a6c13d3-all-of';

/**
 * 
 * @export
 * @interface JobWorkspaceData1005157e3d631000144205466a6c13d3
 */
export interface JobWorkspaceData1005157e3d631000144205466a6c13d3 {
    /**
     * Location chain including bread crumbs for location.
     * @type {string}
     * @memberof JobWorkspaceData1005157e3d631000144205466a6c13d3
     */
    'locationChain'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobWorkspaceData1005157e3d631000144205466a6c13d3
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof JobWorkspaceData1005157e3d631000144205466a6c13d3
     */
    'id'?: string;
}

