/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000AllOf } from './multiple-choice-answers06c0300303a9100019828d5ca44a0000-all-of';

/**
 * 
 * @export
 * @interface MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000
 */
export interface MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000
     */
    'descriptor'?: string;
}

