/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PossibleMultipleChoiceAnswers4c60c128c16510000a59980041610000AllOf
 */
export interface PossibleMultipleChoiceAnswers4c60c128c16510000a59980041610000AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof PossibleMultipleChoiceAnswers4c60c128c16510000a59980041610000AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof PossibleMultipleChoiceAnswers4c60c128c16510000a59980041610000AllOf
     */
    'id'?: string;
}

