/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000AllOf } from './question-multiple-choice-ffdd5de32f7f100016c2c1e768f40000-all-of';

/**
 * 
 * @export
 * @interface QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000
 */
export interface QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000
     */
    'descriptor'?: string;
}

