/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The feedback question type.
 * @export
 * @interface QuestionTypeFfdd5de32f7f1000144df15bb77b0001
 */
export interface QuestionTypeFfdd5de32f7f1000144df15bb77b0001 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof QuestionTypeFfdd5de32f7f1000144df15bb77b0001
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof QuestionTypeFfdd5de32f7f1000144df15bb77b0001
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof QuestionTypeFfdd5de32f7f1000144df15bb77b0001
     */
    'href'?: string;
}

