/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000AllOf
 */
export interface QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000AllOf {
    /**
     * Id of the instance
     * @type {string}
     * @memberof QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000AllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000AllOf
     */
    'descriptor'?: string;
}

