/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The question type used for the question.
 * @export
 * @interface QuestionType544916c1cd75100006c4f105d3f60000
 */
export interface QuestionType544916c1cd75100006c4f105d3f60000 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof QuestionType544916c1cd75100006c4f105d3f60000
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof QuestionType544916c1cd75100006c4f105d3f60000
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof QuestionType544916c1cd75100006c4f105d3f60000
     */
    'href'?: string;
}

