/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RelatesToSummary2c793e888bcd100034b42ada01b20000AllOf
 */
export interface RelatesToSummary2c793e888bcd100034b42ada01b20000AllOf {
    /**
     * The talent tag type for a goal.
     * @type {string}
     * @memberof RelatesToSummary2c793e888bcd100034b42ada01b20000AllOf
     */
    'type'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof RelatesToSummary2c793e888bcd100034b42ada01b20000AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof RelatesToSummary2c793e888bcd100034b42ada01b20000AllOf
     */
    'id'?: string;
}

