/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessProcessParameters9708c966f04f10000e4ae9a03cf80001 } from './business-process-parameters9708c966f04f10000e4ae9a03cf80001';
import { RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000AllOf } from './related-feedback-events9708c966f04f10000e1e9b7f9a5c0000-all-of';

/**
 * 
 * @export
 * @interface RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000
 */
export interface RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000 {
    /**
     * 
     * @type {BusinessProcessParameters9708c966f04f10000e4ae9a03cf80001}
     * @memberof RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000
     */
    'businessProcessParameters'?: BusinessProcessParameters9708c966f04f10000e4ae9a03cf80001;
    /**
     * Id of the instance
     * @type {string}
     * @memberof RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000
     */
    'descriptor'?: string;
}

