/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000 } from './gig-opening-talent-tag-abe398d81e1e1000167d6197a9060000';

/**
 * The talent tag that relates to the gig opening for give feedback event.
 * @export
 * @interface RelatesTo9d12ad407f0f10001c3949add7d40000
 */
export interface RelatesTo9d12ad407f0f10001c3949add7d40000 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof RelatesTo9d12ad407f0f10001c3949add7d40000
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof RelatesTo9d12ad407f0f10001c3949add7d40000
     */
    'id'?: string;
}

