/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RelatesToC836a10b43ed10000beb5b92b4c10000AllOf
 */
export interface RelatesToC836a10b43ed10000beb5b92b4c10000AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof RelatesToC836a10b43ed10000beb5b92b4c10000AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof RelatesToC836a10b43ed10000beb5b92b4c10000AllOf
     */
    'id'?: string;
}

