/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedbackQuestionD396fd5bffec10001393481822cd0007 } from './feedback-question-d396fd5bffec10001393481822cd0007';
import { MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000 } from './multiple-choice-answers06c0300303a9100019828d5ca44a0000';
import { PossibleMultipleChoiceAnswers4c60c128c16510000a59980041610000 } from './possible-multiple-choice-answers4c60c128c16510000a59980041610000';
import { QuestionType544916c1cd75100006c4f105d3f60000 } from './question-type544916c1cd75100006c4f105d3f60000';
import { RelatesToC836a10b43ed10000beb5b92b4c10000 } from './relates-to-c836a10b43ed10000beb5b92b4c10000';
import { RequestedFeedbackCommentsD396fd5bffec10001393477e77870000AllOf } from './requested-feedback-comments-d396fd5bffec10001393477e77870000-all-of';

/**
 * 
 * @export
 * @interface RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
 */
export interface RequestedFeedbackCommentsD396fd5bffec10001393477e77870000 {
    /**
     * Returns True if the responder declined to submit a response to a specific feedback question.
     * @type {boolean}
     * @memberof RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
     */
    'feedbackDeclined'?: boolean;
    /**
     * The reason a requested feedback question was declined.
     * @type {string}
     * @memberof RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
     */
    'feedbackDeclineReason'?: string;
    /**
     * All possible multiple choice answers available to the feedback question.
     * @type {Array<PossibleMultipleChoiceAnswers4c60c128c16510000a59980041610000>}
     * @memberof RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
     */
    'possibleMultipleChoiceAnswers'?: Array<PossibleMultipleChoiceAnswers4c60c128c16510000a59980041610000>;
    /**
     * 
     * @type {QuestionType544916c1cd75100006c4f105d3f60000}
     * @memberof RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
     */
    'questionType'?: QuestionType544916c1cd75100006c4f105d3f60000;
    /**
     * The answers selected from the feedback multiple choice question.
     * @type {Array<MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000>}
     * @memberof RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
     */
    'multipleChoiceAnswers'?: Array<MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000>;
    /**
     * The numeric answer from the Number question type.
     * @type {number}
     * @memberof RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
     */
    'numericAnswer'?: number;
    /**
     * The date answer from the Date question type.
     * @type {string}
     * @memberof RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
     */
    'dateAnswer'?: string;
    /**
     * The feedback response for a feedback question.
     * @type {string}
     * @memberof RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
     */
    'response'?: string;
    /**
     * The talent tags that relate to the feedback question or response.
     * @type {Array<RelatesToC836a10b43ed10000beb5b92b4c10000>}
     * @memberof RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
     */
    'relatesTo'?: Array<RelatesToC836a10b43ed10000beb5b92b4c10000>;
    /**
     * 
     * @type {FeedbackQuestionD396fd5bffec10001393481822cd0007}
     * @memberof RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
     */
    'feedbackQuestion'?: FeedbackQuestionD396fd5bffec10001393481822cd0007;
    /**
     * Id of the instance
     * @type {string}
     * @memberof RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
     */
    'descriptor'?: string;
}

