/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * \\~Worker\\~ issuing feedback request.  If anytime feedback this field is blank.
 * @export
 * @interface RequestedByD396fd5bffec1000100f44a5808f0006
 */
export interface RequestedByD396fd5bffec1000100f44a5808f0006 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof RequestedByD396fd5bffec1000100f44a5808f0006
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof RequestedByD396fd5bffec1000100f44a5808f0006
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof RequestedByD396fd5bffec1000100f44a5808f0006
     */
    'href'?: string;
}

