/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessProcessParameters2b4c8a6ca069100035b85907ae2c0000 } from './business-process-parameters2b4c8a6ca069100035b85907ae2c0000';
import { FeedbackAbout2b4c8a6ca069100035b85907ae2c0002 } from './feedback-about2b4c8a6ca069100035b85907ae2c0002';
import { FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000 } from './feedback-responders-ffdd5de32f7f100016dbb1b188d70000';
import { FeedbackTemplate2b4c8a6ca069100035b859a141200001 } from './feedback-template2b4c8a6ca069100035b859a141200001';
import { RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000 } from './requested-feedback-question-ffdd5de32f7f1000144df0c21e640000';

/**
 * 
 * @export
 * @interface RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
 */
export interface RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf {
    /**
     * 
     * @type {FeedbackAbout2b4c8a6ca069100035b85907ae2c0002}
     * @memberof RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
     */
    'feedbackAbout'?: FeedbackAbout2b4c8a6ca069100035b85907ae2c0002;
    /**
     * Yes if the feedback is confidential between the feedback provider and the manager. Workers don\'t see confidential feedback.
     * @type {boolean}
     * @memberof RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
     */
    'feedbackConfidential'?: boolean;
    /**
     * Overall status of the requested feedback process.
     * @type {string}
     * @memberof RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
     */
    'feedbackOverallStatus'?: string;
    /**
     * Whether to display the name of the responders or have them remain anonymous.ccc
     * @type {boolean}
     * @memberof RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
     */
    'showFeedbackProviderName'?: boolean;
    /**
     * The date the feedback request was initiated.
     * @type {string}
     * @memberof RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
     */
    'requestDate'?: string;
    /**
     * The date the feedback request expires.
     * @type {string}
     * @memberof RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
     */
    'expirationDate'?: string;
    /**
     * Feedback questions used in requested feedback events.
     * @type {Array<RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000>}
     * @memberof RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
     */
    'feedbackQuestions'?: Array<RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000>;
    /**
     * 
     * @type {FeedbackTemplate2b4c8a6ca069100035b859a141200001}
     * @memberof RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
     */
    'feedbackTemplate'?: FeedbackTemplate2b4c8a6ca069100035b859a141200001;
    /**
     * The respondents who\'ve been requested to provide feedback.
     * @type {Array<FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000>}
     * @memberof RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
     */
    'feedbackResponders': Array<FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000>;
    /**
     * 
     * @type {BusinessProcessParameters2b4c8a6ca069100035b85907ae2c0000}
     * @memberof RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
     */
    'businessProcessParameters'?: BusinessProcessParameters2b4c8a6ca069100035b85907ae2c0000;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
     */
    'id'?: string;
}

