/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessProcessParameters4db9c44d36231000134c7a5b6f3b0000 } from './business-process-parameters4db9c44d36231000134c7a5b6f3b0000';
import { FeedbackAbout4db9c44d36231000134c7b8eb3800003 } from './feedback-about4db9c44d36231000134c7b8eb3800003';
import { FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000 } from './feedback-responders-ffdd5de32f7f100016dbb1b188d70000';
import { FeedbackTemplate4db9c44d36231000134c7b8eb3800000 } from './feedback-template4db9c44d36231000134c7b8eb3800000';
import { RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000AllOf } from './requested-feedback-on-self-event-detail19acce0101b310002e6bf03e1bbc0000-all-of';
import { RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000 } from './requested-feedback-question-ffdd5de32f7f1000144df0c21e640000';

/**
 * 
 * @export
 * @interface RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000
 */
export interface RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000 {
    /**
     * 
     * @type {BusinessProcessParameters4db9c44d36231000134c7a5b6f3b0000}
     * @memberof RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000
     */
    'businessProcessParameters'?: BusinessProcessParameters4db9c44d36231000134c7a5b6f3b0000;
    /**
     * Feedback questions used in requested feedback events.
     * @type {Array<RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000>}
     * @memberof RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000
     */
    'feedbackQuestions'?: Array<RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000>;
    /**
     * 
     * @type {FeedbackAbout4db9c44d36231000134c7b8eb3800003}
     * @memberof RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000
     */
    'feedbackAbout'?: FeedbackAbout4db9c44d36231000134c7b8eb3800003;
    /**
     * 
     * @type {FeedbackTemplate4db9c44d36231000134c7b8eb3800000}
     * @memberof RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000
     */
    'feedbackTemplate'?: FeedbackTemplate4db9c44d36231000134c7b8eb3800000;
    /**
     * The date the feedback request expires.
     * @type {string}
     * @memberof RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000
     */
    'expirationDate'?: string;
    /**
     * The date the feedback request was initiated.
     * @type {string}
     * @memberof RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000
     */
    'requestDate'?: string;
    /**
     * Overall status of the requested feedback process.
     * @type {string}
     * @memberof RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000
     */
    'feedbackOverallStatus'?: string;
    /**
     * Private feedback between the feedback provider and the worker. Private feedback isn\'t shared with managers.
     * @type {boolean}
     * @memberof RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000
     */
    'feedbackPrivate'?: boolean;
    /**
     * The respondents who\'ve been requested to provide feedback.
     * @type {Array<FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000>}
     * @memberof RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000
     */
    'feedbackResponders': Array<FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000>;
    /**
     * Whether to display the name of the responders or have them remain anonymous.
     * @type {boolean}
     * @memberof RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000
     */
    'showFeedbackProviderName'?: boolean;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000
     */
    'id'?: string;
}

