/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedbackResponse2f703c317dc910001bd2de83d1590000 } from './feedback-response2f703c317dc910001bd2de83d1590000';
import { QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000 } from './question-multiple-choice-ffdd5de32f7f100016c2c1e768f40000';
import { QuestionTypeFfdd5de32f7f1000144df15bb77b0001 } from './question-type-ffdd5de32f7f1000144df15bb77b0001';
import { RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000AllOf } from './requested-feedback-question-ffdd5de32f7f1000144df0c21e640000-all-of';
import { TalentTagFfdd5de32f7f100016c88e016ad20000 } from './talent-tag-ffdd5de32f7f100016c88e016ad20000';

/**
 * 
 * @export
 * @interface RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000
 */
export interface RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000 {
    /**
     * The talent tags that relate to feedback question or response for requested feedback events.
     * @type {Array<TalentTagFfdd5de32f7f100016c88e016ad20000>}
     * @memberof RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000
     */
    'relatesTo'?: Array<TalentTagFfdd5de32f7f100016c88e016ad20000>;
    /**
     * The rich text part of a Question in a feedback request.
     * @type {string}
     * @memberof RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000
     */
    'question'?: string;
    /**
     * 
     * @type {QuestionTypeFfdd5de32f7f1000144df15bb77b0001}
     * @memberof RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000
     */
    'questionType'?: QuestionTypeFfdd5de32f7f1000144df15bb77b0001;
    /**
     * All the feedback responses for the feedback question.
     * @type {Array<FeedbackResponse2f703c317dc910001bd2de83d1590000>}
     * @memberof RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000
     */
    'feedbackResponse'?: Array<FeedbackResponse2f703c317dc910001bd2de83d1590000>;
    /**
     * Answers for multiple choice questions in requested feedback events.
     * @type {Array<QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000>}
     * @memberof RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000
     */
    'questionMultipleChoiceAnswers'?: Array<QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000>;
    /**
     * Id of the instance
     * @type {string}
     * @memberof RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000
     */
    'descriptor'?: string;
}

