/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SupervisoryOrganizationJobViewFab4a151b24810000d29746fb7e21259AllOf
 */
export interface SupervisoryOrganizationJobViewFab4a151b24810000d29746fb7e21259AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof SupervisoryOrganizationJobViewFab4a151b24810000d29746fb7e21259AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof SupervisoryOrganizationJobViewFab4a151b24810000d29746fb7e21259AllOf
     */
    'id'?: string;
}

