/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SupervisoryOrganizationJobViewFab4a151b24810000d29746fb7e21259 } from './supervisory-organization-job-view-fab4a151b24810000d29746fb7e21259';

/**
 * The \\~supervisory organization\\~ for the position.
 * @export
 * @interface SupervisoryOrganizationB8ac205877fd10000ea91743659800a7
 */
export interface SupervisoryOrganizationB8ac205877fd10000ea91743659800a7 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof SupervisoryOrganizationB8ac205877fd10000ea91743659800a7
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof SupervisoryOrganizationB8ac205877fd10000ea91743659800a7
     */
    'id'?: string;
}

