/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TalentTagFfdd5de32f7f100016c88e016ad20000AllOf } from './talent-tag-ffdd5de32f7f100016c88e016ad20000-all-of';

/**
 * 
 * @export
 * @interface TalentTagFfdd5de32f7f100016c88e016ad20000
 */
export interface TalentTagFfdd5de32f7f100016c88e016ad20000 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof TalentTagFfdd5de32f7f100016c88e016ad20000
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof TalentTagFfdd5de32f7f100016c88e016ad20000
     */
    'descriptor'?: string;
}

