/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The \\~worker\\~ this feedback event is about. This CRF should only be utilized for anytime feedback events.
 * @export
 * @interface ToWorkerF4946919a39f10000f03207b1f230000
 */
export interface ToWorkerF4946919a39f10000f03207b1f230000 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof ToWorkerF4946919a39f10000f03207b1f230000
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof ToWorkerF4946919a39f10000f03207b1f230000
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof ToWorkerF4946919a39f10000f03207b1f230000
     */
    'href'?: string;
}

