/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ERRORMODELREFERENCE } from './errormodelreference';
import { VALIDATIONERRORMODELREFERENCEAllOf } from './validationerrormodelreferenceall-of';

/**
 * 
 * @export
 * @interface VALIDATIONERRORMODELREFERENCE
 */
export interface VALIDATIONERRORMODELREFERENCE {
    /**
     * A description of the error
     * @type {string}
     * @memberof VALIDATIONERRORMODELREFERENCE
     */
    'error': string;
    /**
     * An array of validation errors
     * @type {Array<ERRORMODELREFERENCE>}
     * @memberof VALIDATIONERRORMODELREFERENCE
     */
    'errors'?: Array<ERRORMODELREFERENCE>;
}

