/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GoalsSummary2c793e888bcd100033e663075a2b0000 } from './goals-summary2c793e888bcd100033e663075a2b0000';

/**
 * 
 * @export
 * @interface WorkersGetGoalsResponse
 */
export interface WorkersGetGoalsResponse {
    /**
     * 
     * @type {Array<GoalsSummary2c793e888bcd100033e663075a2b0000>}
     * @memberof WorkersGetGoalsResponse
     */
    'data'?: Array<GoalsSummary2c793e888bcd100033e663075a2b0000>;
    /**
     * 
     * @type {number}
     * @memberof WorkersGetGoalsResponse
     */
    'total'?: number;
}

