/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000 } from './requested-feedback-on-self-event-detail19acce0101b310002e6bf03e1bbc0000';

/**
 * 
 * @export
 * @interface WorkersGetSelfRequestedFeedbackResponse
 */
export interface WorkersGetSelfRequestedFeedbackResponse {
    /**
     * 
     * @type {Array<RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000>}
     * @memberof WorkersGetSelfRequestedFeedbackResponse
     */
    'data'?: Array<RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000>;
    /**
     * 
     * @type {number}
     * @memberof WorkersGetSelfRequestedFeedbackResponse
     */
    'total'?: number;
}

