/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WorkersToNotify9e478586f65410001035b6c26a4c0000AllOf
 */
export interface WorkersToNotify9e478586f65410001035b6c26a4c0000AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof WorkersToNotify9e478586f65410001035b6c26a4c0000AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof WorkersToNotify9e478586f65410001035b6c26a4c0000AllOf
     */
    'id'?: string;
}

