/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkerDataC2466b0778c610000d1936006720000e } from './worker-data-c2466b0778c610000d1936006720000e';

/**
 * 
 * @export
 * @interface WorkersGetCollectionStaffingResponse
 */
export interface WorkersGetCollectionStaffingResponse {
    /**
     * 
     * @type {Array<WorkerDataC2466b0778c610000d1936006720000e>}
     * @memberof WorkersGetCollectionStaffingResponse
     */
    'data'?: Array<WorkerDataC2466b0778c610000d1936006720000e>;
    /**
     * 
     * @type {number}
     * @memberof WorkersGetCollectionStaffingResponse
     */
    'total'?: number;
}

