/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 } from './feedback-event-detail-afd6ac52d62510001086b5c85cd50000';

/**
 * 
 * @export
 * @interface WorkersGetFeedbackEventsResponse
 */
export interface WorkersGetFeedbackEventsResponse {
    /**
     * 
     * @type {Array<FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000>}
     * @memberof WorkersGetFeedbackEventsResponse
     */
    'data'?: Array<FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000>;
    /**
     * 
     * @type {number}
     * @memberof WorkersGetFeedbackEventsResponse
     */
    'total'?: number;
}

