/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000 } from './requested-feedback-on-worker-event-detail2b4c8a6ca069100035b8586e16c20000';

/**
 * 
 * @export
 * @interface WorkersGetRequestedFeedbackEventsResponse
 */
export interface WorkersGetRequestedFeedbackEventsResponse {
    /**
     * 
     * @type {Array<RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000>}
     * @memberof WorkersGetRequestedFeedbackEventsResponse
     */
    'data'?: Array<RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000>;
    /**
     * 
     * @type {number}
     * @memberof WorkersGetRequestedFeedbackEventsResponse
     */
    'total'?: number;
}

