/*
performanceEnablement

The Performance Management service enables applications to access and create feedback about workers in the system.

The version of the OpenAPI document: v5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Returns the \\~Worker\\~ for this \\~Goal\\~.
 * @export
 * @interface Worker47e98fa91eee100017c2c78c80410000
 */
export interface Worker47e98fa91eee100017c2c78c80410000 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof Worker47e98fa91eee100017c2c78c80410000
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof Worker47e98fa91eee100017c2c78c80410000
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof Worker47e98fa91eee100017c2c78c80410000
     */
    'href'?: string;
}

